// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInGimp
{
    internal sealed partial class Vsix
    {
        public const string Id = "AE977542-57A6-448A-89FB-A0915C592A6E";
        public const string Name = "Open in GIMP - GNU Image Manipulation Program";
        public const string Description = @"Open multiple files simultaneously in GIMP (GNU Image Manipulation Program) directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.2.11";
        public const string Author = "GregTrevellick";
        public const string Tags = "open in, gimp, GNU Image Manipulation Program";
    }
}
