// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "82DBDF3D-AC92-4B8C-ABD9-5B69EEF08D22";
        public const string Name = "Open in Visual Studio 2012";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2012 directly from Solution Explorer window.";
        public const string Language = "en-US";
        public const string Version = "1.2.20";
        public const string Author = "Greg Trevellick";
        public const string Tags = "VS2012, Visual Studio 2012";
    }
}
