// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "5bba97c5-4b25-491d-a209-6d0f2e33a8fc";
        public const string Name = "Open in Android Studio";
        public const string Description = @"Open multiple files and more simultaneously in Android Studio directly from Solution Explorer window.";
        public const string Language = "en-US";
        public const string Version = "1.2.19";
        public const string Author = "GregTrevellick";
        public const string Tags = "open; open in; Android Studio; Android; Studio;";
    }
}
