// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "f1f36b5e-0d03-4a23-acb5-493a61340a0b";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);

        public const string guidOpenInAppCmdSetString = "944f543d-5563-46e6-96a3-e4aa5b126729";
        public static Guid guidOpenInAppCmdSet = new Guid(guidOpenInAppCmdSetString);

        public const string guidImagesString = "6f3730d2-9c26-42d4-aef0-68356a6292a7";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenInApp = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}