// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "DF1DFCDF-E0AD-4084-B535-662FC94748BA";
        public const string Name = "Open in Visual Studio 2022";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2022 Community Edition directly from Solution Explorer window.";
        public const string Language = "en-US";
        public const string Version = "1.2.19";
        public const string Author = "GregTrevellick";
        public const string Tags = "VS2022, Visual Studio 2022";
    }
}
