// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "MFA20CC7-7C8E-4E41-B258-539C067E5649";
        public const string Name = "Open in Markdown Monster";
        public const string Description = @"Open multiple files simultaneously in Markdown Monster directly from Solution Explorer or Code Editor window.";
        public const string Language = "en-US";
        public const string Version = "1.2.15";
        public const string Author = "GregTrevellick";
        public const string Tags = "open, open in, MarkdownMonster";
    }
}
