// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "66c6304b-1942-4d4e-8305-e075966d1ef0";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);

        public const string guidOpenInAppCmdSetString = "708a0de2-98e6-43ce-b8f8-472121fb3d17";
        public static Guid guidOpenInAppCmdSet = new Guid(guidOpenInAppCmdSetString);

        public const string guidImagesString = "893f0f26-f856-4d7f-9910-919245929b09";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupOpenInAppCodeWin = 0x1030;
        public const int CmdIdOpenInAppCodeWin = 0x0100;
        public const int GroupOpenInAppItemNode = 0x1040;
        public const int CmdIdOpenInAppItemNode = 0x0110;
        public const int GroupOpenInAppFolderNode = 0x1050;
        public const int CmdIdOpenInAppFolderNode = 0x0120;
        public const int GroupOpenInAppProjNode = 0x1060;
        public const int CmdIdOpenInAppProjNode = 0x0130;
        public const int bmpPic1 = 0x0001;
    }
}