// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "B2C5156F-95D3-4D82-8491-8B3E8B367EC1";
        public const string Name = "Open in Visual Studio 2013";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2013 directly from Solution Explorer window.";
        public const string Language = "en-US";
        public const string Version = "1.2.20";
        public const string Author = "Greg Trevellick";
        public const string Tags = "VS2013, Visual Studio 2013";
    }
}
