// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "4EE49344-F83F-40D8-9901-79C6D5673B71";
        public const string Name = "Open in Visual Studio 2013";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2013 directly from Solution Explorer window.";
        public const string Language = "en-US";
        public const string Version = "1.2.20";
        public const string Author = "Greg Trevellick";
        public const string Tags = "VS2013, Visual Studio 2013";
    }
}
