// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "F131FA59-866A-4630-8031-2F7E6F39D1B8";
        public const string Name = "Open in Visual Studio 2019";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2019 directly from Solution Explorer window.";
        public const string Language = "en-US";
        public const string Version = "1.2.20";
        public const string Author = "GregTrevellick";
        public const string Tags = "VS2019, Visual Studio 2019";
    }
}
