// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "98a5f044-8658-436d-9077-964615402f6a";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);

        public const string guidOpenInAppCmdSetString = "caff4f85-8904-4dde-8e43-1ddaf8ff68c2";
        public static Guid guidOpenInAppCmdSet = new Guid(guidOpenInAppCmdSetString);

        public const string guidImagesString = "32deffa5-7c78-48b6-9867-4233117f59a1";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GroupOpenInAppCodeWin = 0x1030;
        public const int CmdIdOpenInAppCodeWin = 0x0100;
        public const int GroupOpenInAppItemNode = 0x1040;
        public const int CmdIdOpenInAppItemNode = 0x0110;
        public const int GroupOpenInAppFolderNode = 0x1050;
        public const int CmdIdOpenInAppFolderNode = 0x0120;
        public const int GroupOpenInAppProjNode = 0x1060;
        public const int CmdIdOpenInAppProjNode = 0x0130;
        public const int bmpPic1 = 0x0001;
    }
}