// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenInAppPackageString = "389258e7-add6-4709-b7f1-a86531ad8579";
        public static Guid guidOpenInAppPackage = new Guid(guidOpenInAppPackageString);

        public const string guidOpenInAppCmdSetString = "b35b06f9-568e-4b55-9658-aff2460fcddd";
        public static Guid guidOpenInAppCmdSet = new Guid(guidOpenInAppCmdSetString);

        public const string guidImagesString = "a9236bbe-3863-4d25-93ea-3dfd40676ef5";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenInApp = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}