// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "FF68519A-7E7B-4719-9769-3ADA02ABF80D";
        public const string Name = "Open in Visual Studio 2017";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2017 directly from Solution Explorer window.";
        public const string Language = "en-US";
        public const string Version = "1.2.20";
        public const string Author = "Greg Trevellick";
        public const string Tags = "VS2017, Visual Studio 2017";
    }
}
