// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "51818B3F-32D2-4538-BB5B-73A4BEDCB8B5";
        public const string Name = "Open in Visual Studio 2015";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2015 directly from Solution Explorer window.";
        public const string Language = "en-US";
        public const string Version = "1.2.20";
        public const string Author = "Greg Trevellick";
        public const string Tags = "VS2015, Visual Studio 2015";
    }
}
