// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    internal sealed partial class Vsix
    {
        public const string Id = "EB89603B-1419-4A7D-A540-06C33DA7AC6B";
        public const string Name = "Open in Visual Studio 2015";
        public const string Description = @"Open multiple files simultaneously in Visual Studio 2015 directly from Solution Explorer window.";
        public const string Language = "en-US";
        public const string Version = "1.2.20";
        public const string Author = "Greg Trevellick";
        public const string Tags = "VS2015, Visual Studio 2015";
    }
}
